export interface Subcategory {
  id: string;
  name: string;
  description: string;
}

export interface BusinessCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  subcategories: Subcategory[];
}

export const BUSINESS_CATEGORIES: BusinessCategory[] = [
  {
    id: "restaurants-dining",
    name: "Restaurants & Dining",
    icon: "UtensilsCrossed",
    description: "Local restaurants, cafes, and food establishments",
    subcategories: [
      { id: "seafood", name: "Seafood", description: "Fresh catch and seafood restaurants" },
      { id: "bbq-smokehouse", name: "BBQ & Smokehouse", description: "Barbecue and smoked meats" },
      { id: "pizza-italian", name: "Pizza & Italian", description: "Pizza shops and Italian cuisine" },
      { id: "mexican-latin", name: "Mexican & Latin", description: "Mexican and Latin American cuisine" },
      { id: "asian-cuisine", name: "Asian Cuisine", description: "Chinese, Japanese, Thai, and more" },
      { id: "breakfast-brunch", name: "Breakfast & Brunch", description: "Morning and brunch spots" },
      { id: "fast-food", name: "Fast Food & Quick Serve", description: "Drive-thrus and quick service" },
      { id: "fine-dining", name: "Fine Dining", description: "Upscale dining experiences" },
      { id: "cafes-coffee", name: "Cafes & Coffee Shops", description: "Coffee, tea, and light bites" },
      { id: "bakeries", name: "Bakeries & Desserts", description: "Fresh baked goods and sweets" },
      { id: "food-trucks", name: "Food Trucks", description: "Mobile food vendors" },
      { id: "bars-breweries", name: "Bars & Breweries", description: "Craft beer, cocktails, and nightlife" },
      { id: "ice-cream-frozen", name: "Ice Cream & Frozen Treats", description: "Ice cream, gelato, and frozen yogurt" },
      { id: "delis-sandwiches", name: "Delis & Sandwiches", description: "Deli counters and sandwich shops" },
      { id: "catering", name: "Catering Services", description: "Event and party catering" },
      { id: "juice-smoothie", name: "Juice & Smoothie Bars", description: "Fresh juices and smoothies" },
      { id: "vegan-vegetarian", name: "Vegan & Vegetarian", description: "Plant-based dining options" },
      { id: "steakhouse", name: "Steakhouse & Grill", description: "Steaks, burgers, and grilled fare" },
      { id: "waterfront-dining", name: "Waterfront Dining", description: "Dining with water views" },
      { id: "family-restaurants", name: "Family Restaurants", description: "Kid-friendly dining" },
    ],
  },
  {
    id: "home-services",
    name: "Home Services",
    icon: "Home",
    description: "Home repair, maintenance, and improvement",
    subcategories: [
      { id: "general-contractor", name: "General Contractors", description: "Home building and renovation" },
      { id: "plumbing", name: "Plumbing", description: "Pipe repair, water heaters, fixtures" },
      { id: "electrical", name: "Electrical", description: "Wiring, panel upgrades, lighting" },
      { id: "hvac", name: "HVAC", description: "Heating, ventilation, and air conditioning" },
      { id: "roofing", name: "Roofing", description: "Roof repair and replacement" },
      { id: "painting", name: "Painting", description: "Interior and exterior painting" },
      { id: "flooring", name: "Flooring", description: "Hardwood, tile, carpet installation" },
      { id: "carpentry", name: "Carpentry", description: "Custom woodwork and framing" },
      { id: "drywall", name: "Drywall & Plastering", description: "Wall repair and installation" },
      { id: "insulation", name: "Insulation", description: "Home insulation services" },
      { id: "siding", name: "Siding & Gutters", description: "Exterior siding and gutter work" },
      { id: "fencing", name: "Fencing", description: "Fence installation and repair" },
      { id: "decks-patios", name: "Decks & Patios", description: "Outdoor living spaces" },
      { id: "pressure-washing", name: "Pressure Washing", description: "Exterior cleaning services" },
      { id: "handyman", name: "Handyman Services", description: "General repairs and odd jobs" },
      { id: "storm-damage", name: "Storm Damage Repair", description: "Hurricane and storm restoration" },
      { id: "windows-doors", name: "Windows & Doors", description: "Window and door installation" },
      { id: "chimney", name: "Chimney Services", description: "Chimney cleaning and repair" },
      { id: "foundation", name: "Foundation Repair", description: "Foundation and structural work" },
      { id: "home-inspection", name: "Home Inspection", description: "Pre-purchase and maintenance inspections" },
    ],
  },
  {
    id: "automotive",
    name: "Automotive",
    icon: "Car",
    description: "Vehicle sales, repair, and services",
    subcategories: [
      { id: "auto-repair", name: "Auto Repair & Mechanics", description: "General auto repair" },
      { id: "tire-shops", name: "Tire Shops", description: "Tire sales and service" },
      { id: "oil-change", name: "Oil Change & Lube", description: "Quick oil changes" },
      { id: "body-shops", name: "Body Shops & Collision", description: "Collision repair and paint" },
      { id: "auto-detailing", name: "Auto Detailing", description: "Interior and exterior detailing" },
      { id: "car-dealerships", name: "Car Dealerships", description: "New and used car sales" },
      { id: "towing", name: "Towing Services", description: "Roadside and towing assistance" },
      { id: "transmission", name: "Transmission Repair", description: "Transmission specialists" },
      { id: "brakes", name: "Brake Services", description: "Brake repair and replacement" },
      { id: "auto-glass", name: "Auto Glass", description: "Windshield repair and replacement" },
      { id: "car-wash", name: "Car Wash", description: "Automated and hand car washes" },
      { id: "auto-parts", name: "Auto Parts & Accessories", description: "Parts stores and accessories" },
      { id: "boat-marine", name: "Boat & Marine Services", description: "Boat repair and maintenance" },
      { id: "motorcycle", name: "Motorcycle Services", description: "Motorcycle repair and sales" },
      { id: "rv-camper", name: "RV & Camper Services", description: "RV repair and maintenance" },
      { id: "golf-cart", name: "Golf Cart Sales & Repair", description: "Golf cart specialists" },
      { id: "alignment", name: "Wheel Alignment", description: "Alignment and suspension work" },
      { id: "exhaust-muffler", name: "Exhaust & Muffler", description: "Exhaust system services" },
      { id: "ac-repair-auto", name: "Auto AC Repair", description: "Vehicle AC service" },
      { id: "diesel-services", name: "Diesel Services", description: "Diesel engine specialists" },
      { id: "window-tinting", name: "Window Tinting", description: "Auto and residential window tinting" },
    ],
  },
  {
    id: "health-wellness",
    name: "Health & Wellness",
    icon: "HeartPulse",
    description: "Medical, dental, and wellness providers",
    subcategories: [
      { id: "family-medicine", name: "Family Medicine", description: "Primary care physicians" },
      { id: "dentistry", name: "Dentistry", description: "Dental care and cosmetic dentistry" },
      { id: "optometry", name: "Optometry & Vision", description: "Eye care and glasses" },
      { id: "chiropractic", name: "Chiropractic", description: "Spinal adjustments and care" },
      { id: "physical-therapy", name: "Physical Therapy", description: "Rehabilitation services" },
      { id: "mental-health", name: "Mental Health & Counseling", description: "Therapy and counseling" },
      { id: "dermatology", name: "Dermatology", description: "Skin care specialists" },
      { id: "pharmacy", name: "Pharmacy", description: "Prescription and OTC medications" },
      { id: "urgent-care", name: "Urgent Care", description: "Walk-in medical care" },
      { id: "veterinary", name: "Veterinary Care", description: "Pet and animal health" },
      { id: "massage-therapy", name: "Massage Therapy", description: "Therapeutic massage" },
      { id: "acupuncture", name: "Acupuncture", description: "Traditional acupuncture services" },
      { id: "nutrition", name: "Nutrition & Dietetics", description: "Diet and nutrition counseling" },
      { id: "home-health", name: "Home Health Care", description: "In-home medical services" },
      { id: "pediatrics", name: "Pediatrics", description: "Children's health care" },
      { id: "senior-care", name: "Senior Care", description: "Elder care services" },
      { id: "medical-equipment", name: "Medical Equipment", description: "Medical supply stores" },
      { id: "podiatry", name: "Podiatry", description: "Foot and ankle care" },
      { id: "orthopedics", name: "Orthopedics", description: "Bone and joint specialists" },
      { id: "allergy-immunology", name: "Allergy & Immunology", description: "Allergy testing and treatment" },
    ],
  },
  {
    id: "beauty-personal-care",
    name: "Beauty & Personal Care",
    icon: "Scissors",
    description: "Salons, spas, and personal grooming",
    subcategories: [
      { id: "hair-salons", name: "Hair Salons", description: "Haircuts, color, and styling" },
      { id: "barbershops", name: "Barbershops", description: "Men's grooming and haircuts" },
      { id: "nail-salons", name: "Nail Salons", description: "Manicures, pedicures, nail art" },
      { id: "day-spas", name: "Day Spas", description: "Spa treatments and relaxation" },
      { id: "tanning", name: "Tanning Salons", description: "Indoor tanning and spray tan" },
      { id: "waxing", name: "Waxing Services", description: "Hair removal services" },
      { id: "lashes-brows", name: "Lashes & Brows", description: "Eyelash extensions and brow styling" },
      { id: "skincare", name: "Skincare & Facials", description: "Professional skincare treatments" },
      { id: "tattoo-piercing", name: "Tattoo & Piercing", description: "Body art and piercings" },
      { id: "makeup-artist", name: "Makeup Artists", description: "Professional makeup services" },
      { id: "med-spa", name: "Med Spa", description: "Medical aesthetic treatments" },
      { id: "beauty-supply", name: "Beauty Supply Stores", description: "Beauty products and tools" },
      { id: "hair-extensions", name: "Hair Extensions", description: "Extension installation and care" },
      { id: "mens-grooming", name: "Men's Grooming", description: "Premium men's care services" },
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    icon: "Building2",
    description: "Property sales, rentals, and management",
    subcategories: [
      { id: "residential-sales", name: "Residential Sales", description: "Home buying and selling" },
      { id: "commercial-real-estate", name: "Commercial Real Estate", description: "Business properties" },
      { id: "property-management", name: "Property Management", description: "Rental property management" },
      { id: "vacation-rentals", name: "Vacation Rentals", description: "Short-term rental properties" },
      { id: "real-estate-agents", name: "Real Estate Agents", description: "Licensed buyer/seller agents" },
      { id: "mortgage-lending", name: "Mortgage & Lending", description: "Home loans and financing" },
      { id: "title-closing", name: "Title & Closing", description: "Title search and closing services" },
      { id: "appraisal", name: "Appraisal Services", description: "Property valuation" },
      { id: "land-lots", name: "Land & Lots", description: "Undeveloped land sales" },
      { id: "new-construction", name: "New Construction", description: "New home builders" },
      { id: "home-staging", name: "Home Staging", description: "Property staging for sale" },
      { id: "relocation", name: "Relocation Services", description: "Moving and relocation assistance" },
      { id: "hoa-management", name: "HOA Management", description: "Homeowner association services" },
      { id: "rental-listings", name: "Rental Listings", description: "Long-term rental properties" },
    ],
  },
  {
    id: "legal-services",
    name: "Legal Services",
    icon: "Scale",
    description: "Attorneys and legal professionals",
    subcategories: [
      { id: "personal-injury", name: "Personal Injury", description: "Accident and injury claims" },
      { id: "family-law", name: "Family Law", description: "Divorce, custody, and family matters" },
      { id: "criminal-defense", name: "Criminal Defense", description: "Criminal case representation" },
      { id: "estate-planning", name: "Estate Planning", description: "Wills, trusts, and probate" },
      { id: "business-law", name: "Business Law", description: "Corporate and business legal services" },
      { id: "real-estate-law", name: "Real Estate Law", description: "Property transactions and disputes" },
      { id: "immigration", name: "Immigration Law", description: "Visa and immigration services" },
      { id: "bankruptcy", name: "Bankruptcy", description: "Debt relief and bankruptcy filing" },
      { id: "traffic-dui", name: "Traffic & DUI", description: "Traffic violations and DUI defense" },
      { id: "workers-comp", name: "Workers' Compensation", description: "Workplace injury claims" },
      { id: "tax-law", name: "Tax Law", description: "Tax disputes and planning" },
      { id: "notary", name: "Notary Services", description: "Document notarization" },
      { id: "mediation", name: "Mediation & Arbitration", description: "Alternative dispute resolution" },
      { id: "elder-law", name: "Elder Law", description: "Senior legal services" },
    ],
  },
  {
    id: "financial-services",
    name: "Financial Services",
    icon: "Landmark",
    description: "Banking, insurance, and financial planning",
    subcategories: [
      { id: "banking", name: "Banks & Credit Unions", description: "Banking and financial institutions" },
      { id: "insurance-auto", name: "Auto Insurance", description: "Vehicle insurance policies" },
      { id: "insurance-home", name: "Home Insurance", description: "Homeowner and renter insurance" },
      { id: "insurance-life", name: "Life Insurance", description: "Life and health insurance" },
      { id: "financial-planning", name: "Financial Planning", description: "Investment and retirement planning" },
      { id: "tax-preparation", name: "Tax Preparation", description: "Tax filing and accounting" },
      { id: "bookkeeping", name: "Bookkeeping", description: "Small business bookkeeping" },
      { id: "cpa", name: "CPA & Accounting", description: "Certified public accountants" },
      { id: "payroll", name: "Payroll Services", description: "Business payroll processing" },
      { id: "wealth-management", name: "Wealth Management", description: "High-net-worth advisory" },
      { id: "loans-credit", name: "Loans & Credit", description: "Personal and business loans" },
      { id: "collections", name: "Collections", description: "Debt collection services" },
      { id: "financial-coaching", name: "Financial Coaching", description: "Personal finance education" },
      { id: "insurance-commercial", name: "Commercial Insurance", description: "Business insurance solutions" },
    ],
  },
  {
    id: "education-tutoring",
    name: "Education & Tutoring",
    icon: "GraduationCap",
    description: "Schools, tutors, and learning centers",
    subcategories: [
      { id: "private-schools", name: "Private Schools", description: "K-12 private education" },
      { id: "preschool-daycare", name: "Preschool & Daycare", description: "Early childhood education" },
      { id: "tutoring", name: "Tutoring Services", description: "Academic tutoring" },
      { id: "test-prep", name: "Test Prep", description: "SAT, ACT, and exam preparation" },
      { id: "music-lessons", name: "Music Lessons", description: "Instrument and voice instruction" },
      { id: "art-classes", name: "Art Classes", description: "Visual arts education" },
      { id: "dance-studios", name: "Dance Studios", description: "Dance classes and instruction" },
      { id: "martial-arts", name: "Martial Arts Schools", description: "Karate, judo, and self-defense" },
      { id: "driving-schools", name: "Driving Schools", description: "Driver education and training" },
      { id: "language-classes", name: "Language Classes", description: "Foreign language instruction" },
      { id: "swim-lessons", name: "Swim Lessons", description: "Swimming instruction" },
      { id: "stem-programs", name: "STEM Programs", description: "Science and technology education" },
      { id: "special-education", name: "Special Education", description: "Learning disability support" },
      { id: "adult-education", name: "Adult Education", description: "Continuing education programs" },
      { id: "trade-schools", name: "Trade Schools", description: "Vocational and trade training" },
      { id: "online-learning", name: "Online Learning", description: "Virtual education platforms" },
    ],
  },
  {
    id: "fitness-recreation",
    name: "Fitness & Recreation",
    icon: "Dumbbell",
    description: "Gyms, sports, and outdoor activities",
    subcategories: [
      { id: "gyms", name: "Gyms & Fitness Centers", description: "Workout facilities" },
      { id: "yoga-pilates", name: "Yoga & Pilates", description: "Yoga and pilates studios" },
      { id: "crossfit", name: "CrossFit & Boot Camp", description: "High-intensity training" },
      { id: "personal-training", name: "Personal Training", description: "One-on-one fitness coaching" },
      { id: "golf-courses", name: "Golf Courses", description: "Public and private golf" },
      { id: "surf-shops", name: "Surf Shops & Lessons", description: "Surfing gear and instruction" },
      { id: "kayak-paddle", name: "Kayak & Paddleboard", description: "Water sports rentals" },
      { id: "fishing-charters", name: "Fishing Charters", description: "Deep sea and inshore fishing" },
      { id: "horse-stables", name: "Horse Stables & Riding", description: "Horseback riding and boarding" },
      { id: "bowling", name: "Bowling Alleys", description: "Bowling and entertainment" },
      { id: "mini-golf", name: "Mini Golf & Attractions", description: "Family entertainment" },
      { id: "bike-shops", name: "Bike Shops & Rentals", description: "Bicycle sales and rentals" },
      { id: "hunting-outdoor", name: "Hunting & Outdoor Sports", description: "Hunting guides and outfitters" },
      { id: "skating-rinks", name: "Skating Rinks", description: "Ice and roller skating" },
      { id: "tennis-pickleball", name: "Tennis & Pickleball", description: "Racquet sports facilities" },
      { id: "water-parks", name: "Water Parks", description: "Aquatic recreation" },
      { id: "boat-rentals", name: "Boat Rentals", description: "Boat and jet ski rentals" },
      { id: "rock-climbing", name: "Rock Climbing", description: "Indoor and outdoor climbing" },
      { id: "campgrounds", name: "Campgrounds", description: "Camping and RV parks" },
      { id: "nature-tours", name: "Nature Tours", description: "Eco tours and wildlife viewing" },
    ],
  },
  {
    id: "shopping-retail",
    name: "Shopping & Retail",
    icon: "ShoppingBag",
    description: "Stores, boutiques, and retail shops",
    subcategories: [
      { id: "clothing-boutiques", name: "Clothing Boutiques", description: "Fashion and apparel" },
      { id: "gift-shops", name: "Gift Shops", description: "Souvenirs and gifts" },
      { id: "jewelry", name: "Jewelry Stores", description: "Fine jewelry and watches" },
      { id: "antiques", name: "Antiques & Vintage", description: "Antique stores and collectibles" },
      { id: "home-decor", name: "Home Decor & Furniture", description: "Interior furnishings" },
      { id: "sporting-goods", name: "Sporting Goods", description: "Sports equipment and gear" },
      { id: "electronics", name: "Electronics", description: "Computers, phones, and gadgets" },
      { id: "grocery-stores", name: "Grocery Stores", description: "Food and grocery shopping" },
      { id: "farmers-markets", name: "Farmers Markets", description: "Local produce and artisan goods" },
      { id: "pet-stores", name: "Pet Stores & Supplies", description: "Pet food, toys, and supplies" },
      { id: "hardware-stores", name: "Hardware Stores", description: "Tools and home improvement" },
      { id: "thrift-stores", name: "Thrift & Consignment", description: "Secondhand and resale shops" },
      { id: "bookstores", name: "Bookstores", description: "Books and reading materials" },
      { id: "florists", name: "Florists", description: "Fresh flowers and arrangements" },
      { id: "nurseries-garden", name: "Nurseries & Garden", description: "Plants and garden supplies" },
      { id: "smoke-vape", name: "Smoke & Vape Shops", description: "Tobacco and vape products" },
      { id: "surf-beach-shops", name: "Surf & Beach Shops", description: "Beach gear and swimwear" },
      { id: "toy-stores", name: "Toy Stores", description: "Toys, games, and hobbies" },
      { id: "art-galleries", name: "Art Galleries", description: "Fine art and local artists" },
      { id: "wine-liquor", name: "Wine & Liquor Stores", description: "Alcoholic beverages" },
    ],
  },
  {
    id: "pet-services",
    name: "Pet Services",
    icon: "PawPrint",
    description: "Pet care, grooming, and training",
    subcategories: [
      { id: "pet-grooming", name: "Pet Grooming", description: "Bathing, haircuts, and styling" },
      { id: "dog-training", name: "Dog Training", description: "Obedience and behavior training" },
      { id: "pet-boarding", name: "Pet Boarding & Kennels", description: "Overnight pet care" },
      { id: "pet-sitting", name: "Pet Sitting & Walking", description: "In-home pet care and walks" },
      { id: "pet-daycare", name: "Pet Daycare", description: "Daytime pet supervision" },
      { id: "pet-adoption", name: "Pet Adoption & Rescue", description: "Animal rescue organizations" },
      { id: "aquarium-fish", name: "Aquarium & Fish", description: "Aquarium supplies and fish" },
      { id: "pet-photography", name: "Pet Photography", description: "Professional pet portraits" },
      { id: "mobile-vet", name: "Mobile Veterinary", description: "In-home vet services" },
      { id: "pet-cremation", name: "Pet Cremation & Memorial", description: "Pet end-of-life services" },
    ],
  },
  {
    id: "wedding-events",
    name: "Wedding & Events",
    icon: "PartyPopper",
    description: "Wedding planning and event services",
    subcategories: [
      { id: "wedding-venues", name: "Wedding Venues", description: "Ceremony and reception locations" },
      { id: "wedding-planners", name: "Wedding Planners", description: "Full-service wedding coordination" },
      { id: "photographers", name: "Photographers", description: "Wedding and event photography" },
      { id: "videographers", name: "Videographers", description: "Wedding and event videography" },
      { id: "djs-entertainment", name: "DJs & Entertainment", description: "Music and entertainment" },
      { id: "florists-wedding", name: "Wedding Florists", description: "Bridal bouquets and decor" },
      { id: "wedding-catering", name: "Wedding Catering", description: "Reception food service" },
      { id: "wedding-cakes", name: "Wedding Cakes", description: "Custom wedding cakes" },
      { id: "bridal-shops", name: "Bridal Shops", description: "Wedding gowns and attire" },
      { id: "event-rentals", name: "Event Rentals", description: "Tents, tables, and chairs" },
      { id: "invitations", name: "Invitations & Stationery", description: "Custom printing and design" },
      { id: "photo-booth", name: "Photo Booth Rentals", description: "Event photo booths" },
      { id: "officiant", name: "Wedding Officiants", description: "Ceremony officiants" },
      { id: "party-planning", name: "Party Planning", description: "Birthday and special event planning" },
      { id: "balloon-decor", name: "Balloon & Decor", description: "Event decorations" },
      { id: "limo-transport", name: "Limo & Transport", description: "Event transportation" },
    ],
  },
  {
    id: "cleaning-services",
    name: "Cleaning Services",
    icon: "SparkleIcon",
    description: "Residential and commercial cleaning",
    subcategories: [
      { id: "house-cleaning", name: "House Cleaning", description: "Regular home cleaning" },
      { id: "deep-cleaning", name: "Deep Cleaning", description: "Thorough deep clean services" },
      { id: "carpet-cleaning", name: "Carpet Cleaning", description: "Carpet and upholstery cleaning" },
      { id: "window-cleaning", name: "Window Cleaning", description: "Professional window washing" },
      { id: "commercial-cleaning", name: "Commercial Cleaning", description: "Office and business cleaning" },
      { id: "move-in-out", name: "Move-In/Move-Out Cleaning", description: "Rental turnover cleaning" },
      { id: "vacation-rental-clean", name: "Vacation Rental Cleaning", description: "Airbnb/VRBO turnover" },
      { id: "mold-remediation", name: "Mold Remediation", description: "Mold removal and prevention" },
      { id: "junk-removal", name: "Junk Removal", description: "Hauling and disposal services" },
      { id: "laundry-services", name: "Laundry Services", description: "Wash, fold, and dry cleaning" },
      { id: "pool-cleaning", name: "Pool Cleaning", description: "Swimming pool maintenance" },
      { id: "air-duct-cleaning", name: "Air Duct Cleaning", description: "HVAC duct cleaning" },
    ],
  },
  {
    id: "landscaping",
    name: "Landscaping & Lawn Care",
    icon: "TreePine",
    description: "Yard work, landscaping, and outdoor services",
    subcategories: [
      { id: "lawn-mowing", name: "Lawn Mowing", description: "Regular lawn maintenance" },
      { id: "landscape-design", name: "Landscape Design", description: "Custom landscape planning" },
      { id: "tree-service", name: "Tree Service", description: "Tree removal and trimming" },
      { id: "irrigation", name: "Irrigation Systems", description: "Sprinkler installation and repair" },
      { id: "mulching", name: "Mulching & Bed Maintenance", description: "Garden bed care" },
      { id: "hardscaping", name: "Hardscaping", description: "Patios, walkways, retaining walls" },
      { id: "sod-seeding", name: "Sod & Seeding", description: "Lawn installation" },
      { id: "leaf-removal", name: "Leaf Removal", description: "Seasonal leaf cleanup" },
      { id: "stump-grinding", name: "Stump Grinding", description: "Stump removal services" },
      { id: "pest-control-lawn", name: "Lawn Pest Control", description: "Turf pest treatment" },
      { id: "outdoor-lighting", name: "Outdoor Lighting", description: "Landscape lighting design" },
      { id: "drainage", name: "Drainage Solutions", description: "Yard drainage systems" },
      { id: "snow-removal", name: "Snow Removal", description: "Snow plowing and ice management" },
      { id: "weed-control", name: "Weed Control & Fertilization", description: "Lawn treatment programs" },
    ],
  },
  {
    id: "technology",
    name: "Technology & IT",
    icon: "Monitor",
    description: "Computer repair, IT services, and tech support",
    subcategories: [
      { id: "computer-repair", name: "Computer Repair", description: "PC and Mac repair" },
      { id: "phone-repair", name: "Phone Repair", description: "Smartphone screen and battery repair" },
      { id: "it-support", name: "IT Support", description: "Business IT services" },
      { id: "web-design", name: "Web Design", description: "Website design and development" },
      { id: "seo-marketing", name: "SEO & Digital Marketing", description: "Online marketing services" },
      { id: "social-media-mgmt", name: "Social Media Management", description: "Social media marketing" },
      { id: "network-setup", name: "Network Setup", description: "WiFi and network installation" },
      { id: "data-recovery", name: "Data Recovery", description: "Lost data retrieval" },
      { id: "cybersecurity", name: "Cybersecurity", description: "Security consulting" },
      { id: "app-development", name: "App Development", description: "Mobile app creation" },
      { id: "graphic-design", name: "Graphic Design", description: "Logo, branding, and print design" },
      { id: "video-production", name: "Video Production", description: "Commercial video and editing" },
      { id: "smart-home", name: "Smart Home Installation", description: "Home automation" },
      { id: "surveillance", name: "Security Cameras & Surveillance", description: "Camera installation" },
    ],
  },
  {
    id: "travel-tourism",
    name: "Travel & Tourism",
    icon: "Plane",
    description: "Hotels, tours, and travel services",
    subcategories: [
      { id: "hotels-motels", name: "Hotels & Motels", description: "Overnight accommodations" },
      { id: "bed-breakfast", name: "Bed & Breakfast", description: "B&B lodging" },
      { id: "vacation-homes", name: "Vacation Home Rentals", description: "VRBO and Airbnb properties" },
      { id: "tour-guides", name: "Tour Guides", description: "Local sightseeing tours" },
      { id: "travel-agencies", name: "Travel Agencies", description: "Trip planning and booking" },
      { id: "charter-boats", name: "Charter Boats", description: "Boat charter services" },
      { id: "eco-tours", name: "Eco Tours", description: "Environmental and nature tours" },
      { id: "helicopter-tours", name: "Helicopter Tours", description: "Aerial sightseeing" },
      { id: "beach-equipment", name: "Beach Equipment Rental", description: "Chairs, umbrellas, and gear" },
      { id: "segway-tours", name: "Segway & Bike Tours", description: "Guided cycling tours" },
      { id: "ghost-tours", name: "Ghost & History Tours", description: "Historical walking tours" },
      { id: "airport-shuttle", name: "Airport Shuttle", description: "Airport transportation" },
      { id: "concierge", name: "Concierge Services", description: "Personal travel assistance" },
      { id: "campground-rv", name: "Campgrounds & RV Parks", description: "Outdoor lodging" },
    ],
  },
  {
    id: "moving-storage",
    name: "Moving & Storage",
    icon: "Truck",
    description: "Moving companies and storage facilities",
    subcategories: [
      { id: "local-movers", name: "Local Movers", description: "In-town moving services" },
      { id: "long-distance", name: "Long Distance Moving", description: "Interstate moving" },
      { id: "packing-services", name: "Packing Services", description: "Professional packing" },
      { id: "storage-units", name: "Storage Units", description: "Self-storage facilities" },
      { id: "portable-storage", name: "Portable Storage", description: "PODS and mobile containers" },
      { id: "truck-rental", name: "Truck Rental", description: "Moving truck rentals" },
      { id: "piano-moving", name: "Piano & Specialty Moving", description: "Heavy item transport" },
      { id: "boat-storage", name: "Boat Storage", description: "Indoor and outdoor boat storage" },
      { id: "rv-storage", name: "RV Storage", description: "RV parking and storage" },
      { id: "climate-controlled", name: "Climate-Controlled Storage", description: "Temperature-regulated units" },
    ],
  },
  {
    id: "pest-control",
    name: "Pest Control",
    icon: "Bug",
    description: "Extermination and pest management",
    subcategories: [
      { id: "general-pest", name: "General Pest Control", description: "Ants, roaches, spiders" },
      { id: "termite", name: "Termite Treatment", description: "Termite inspection and treatment" },
      { id: "mosquito-control", name: "Mosquito Control", description: "Mosquito spraying and prevention" },
      { id: "rodent-control", name: "Rodent Control", description: "Mice and rat removal" },
      { id: "bed-bugs", name: "Bed Bug Treatment", description: "Bed bug extermination" },
      { id: "wildlife-removal", name: "Wildlife Removal", description: "Raccoon, snake, and animal removal" },
      { id: "bee-wasp", name: "Bee & Wasp Removal", description: "Stinging insect removal" },
      { id: "flea-tick", name: "Flea & Tick Treatment", description: "Home flea treatment" },
      { id: "crawl-space", name: "Crawl Space Encapsulation", description: "Moisture and pest barriers" },
      { id: "commercial-pest", name: "Commercial Pest Control", description: "Business pest management" },
    ],
  },
  {
    id: "photography",
    name: "Photography & Video",
    icon: "Camera",
    description: "Professional photography and videography",
    subcategories: [
      { id: "portrait-photo", name: "Portrait Photography", description: "Individual and family portraits" },
      { id: "event-photo", name: "Event Photography", description: "Special event coverage" },
      { id: "real-estate-photo", name: "Real Estate Photography", description: "Property listing photos" },
      { id: "drone-photo", name: "Drone Photography", description: "Aerial photos and video" },
      { id: "headshots", name: "Professional Headshots", description: "Corporate and acting headshots" },
      { id: "product-photo", name: "Product Photography", description: "E-commerce and catalog photos" },
      { id: "newborn-maternity", name: "Newborn & Maternity", description: "Baby and maternity sessions" },
      { id: "senior-photos", name: "Senior Portraits", description: "High school senior photos" },
      { id: "commercial-video", name: "Commercial Video", description: "Business promotional videos" },
      { id: "documentary", name: "Documentary Filmmaking", description: "Documentary production" },
    ],
  },
  {
    id: "religious-spiritual",
    name: "Religious & Spiritual",
    icon: "Church",
    description: "Churches, temples, and spiritual organizations",
    subcategories: [
      { id: "churches", name: "Churches", description: "Christian churches and worship" },
      { id: "synagogues", name: "Synagogues", description: "Jewish temples and congregations" },
      { id: "mosques", name: "Mosques", description: "Islamic worship centers" },
      { id: "hindu-temples", name: "Hindu Temples", description: "Hindu worship centers" },
      { id: "buddhist-centers", name: "Buddhist Centers", description: "Buddhist meditation and practice" },
      { id: "spiritual-centers", name: "Spiritual Centers", description: "Interfaith and spiritual groups" },
      { id: "youth-ministry", name: "Youth Ministry", description: "Youth faith programs" },
      { id: "religious-ed", name: "Religious Education", description: "Faith-based learning" },
      { id: "counseling-faith", name: "Faith-Based Counseling", description: "Spiritual counseling" },
      { id: "community-outreach", name: "Community Outreach", description: "Faith-based community programs" },
    ],
  },
  {
    id: "government-nonprofit",
    name: "Government & Nonprofit",
    icon: "Landmark",
    description: "Government offices and nonprofit organizations",
    subcategories: [
      { id: "county-offices", name: "County Government Offices", description: "Currituck County departments" },
      { id: "town-offices", name: "Town & City Offices", description: "Municipal government" },
      { id: "post-offices", name: "Post Offices", description: "USPS locations" },
      { id: "dmv", name: "DMV & Tag Offices", description: "Vehicle registration" },
      { id: "libraries", name: "Public Libraries", description: "Library branches" },
      { id: "parks-rec", name: "Parks & Recreation", description: "Public parks and programs" },
      { id: "fire-dept", name: "Fire Departments", description: "Fire and rescue stations" },
      { id: "police-sheriff", name: "Police & Sheriff", description: "Law enforcement" },
      { id: "food-banks", name: "Food Banks", description: "Food assistance programs" },
      { id: "animal-shelters", name: "Animal Shelters", description: "County animal services" },
      { id: "community-centers", name: "Community Centers", description: "Public gathering spaces" },
      { id: "veterans-services", name: "Veterans Services", description: "Veteran support organizations" },
    ],
  },
  {
    id: "child-care",
    name: "Child Care & Family",
    icon: "Baby",
    description: "Childcare, family activities, and parenting resources",
    subcategories: [
      { id: "daycare-centers", name: "Daycare Centers", description: "Full-day child care" },
      { id: "nannies", name: "Nannies & Babysitters", description: "In-home child care" },
      { id: "after-school", name: "After-School Programs", description: "After-school care and activities" },
      { id: "summer-camps", name: "Summer Camps", description: "Day and overnight camps" },
      { id: "family-activities", name: "Family Activities", description: "Family-friendly entertainment" },
      { id: "kids-parties", name: "Kids Party Venues", description: "Birthday party locations" },
      { id: "play-areas", name: "Indoor Play Areas", description: "Indoor playgrounds" },
      { id: "parenting-classes", name: "Parenting Classes", description: "Parenting workshops and support" },
      { id: "tutoring-kids", name: "Kids Tutoring", description: "Elementary age tutoring" },
      { id: "special-needs", name: "Special Needs Services", description: "Specialized care and support" },
    ],
  },
  {
    id: "security-services",
    name: "Security Services",
    icon: "Shield",
    description: "Security systems and guard services",
    subcategories: [
      { id: "home-security", name: "Home Security Systems", description: "Alarm and monitoring" },
      { id: "commercial-security", name: "Commercial Security", description: "Business security solutions" },
      { id: "security-guards", name: "Security Guards", description: "On-site security personnel" },
      { id: "access-control", name: "Access Control", description: "Keycard and gate systems" },
      { id: "fire-alarms", name: "Fire Alarm Systems", description: "Fire detection and monitoring" },
      { id: "locksmith", name: "Locksmith Services", description: "Lock installation and emergencies" },
      { id: "safe-vault", name: "Safe & Vault Services", description: "Safe sales and service" },
      { id: "patrol-services", name: "Patrol Services", description: "Mobile security patrols" },
    ],
  },
  {
    id: "animal-pet",
    name: "Animal & Pet",
    icon: "PawPrint",
    description: "Animal care, pet services, and veterinary",
    subcategories: [
      { id: "pet-grooming-animal", name: "Pet Grooming", description: "Bathing, haircuts, and styling" },
      { id: "veterinary-animal", name: "Veterinary Services", description: "Animal health and medical care" },
      { id: "pet-boarding-animal", name: "Pet Boarding", description: "Overnight and extended pet care" },
      { id: "pet-training-animal", name: "Pet Training", description: "Obedience and behavior training" },
      { id: "pet-sitting-animal", name: "Pet Sitting & Walking", description: "In-home pet care and dog walking" },
      { id: "pet-supplies-animal", name: "Pet Supplies", description: "Food, toys, and accessories" },
      { id: "animal-rescue", name: "Animal Rescue & Adoption", description: "Rescue organizations and shelters" },
      { id: "equine-services", name: "Equine Services", description: "Horse care, boarding, and farrier" },
      { id: "exotic-pets", name: "Exotic Pet Services", description: "Care for reptiles, birds, and exotic animals" },
      { id: "mobile-vet-animal", name: "Mobile Veterinary", description: "In-home veterinary visits" },
    ],
  },
  {
    id: "garage-door",
    name: "Garage Door",
    icon: "DoorOpen",
    description: "Garage door installation, repair, and maintenance",
    subcategories: [
      { id: "garage-door-install", name: "Garage Door Installation", description: "New garage door installation" },
      { id: "garage-door-repair", name: "Garage Door Repair", description: "Spring, opener, and panel repair" },
      { id: "garage-door-opener", name: "Garage Door Openers", description: "Opener installation and replacement" },
      { id: "garage-door-spring", name: "Spring Replacement", description: "Torsion and extension spring repair" },
      { id: "garage-door-commercial", name: "Commercial Garage Doors", description: "Industrial and commercial doors" },
      { id: "garage-door-maintenance", name: "Preventive Maintenance", description: "Regular maintenance and tune-ups" },
      { id: "garage-door-custom", name: "Custom Garage Doors", description: "Custom designed garage doors" },
      { id: "garage-door-insulation", name: "Garage Door Insulation", description: "Insulation upgrades and weatherproofing" },
    ],
  },
  {
    id: "moving-hauling",
    name: "Moving & Hauling",
    icon: "Truck",
    description: "Moving services, hauling, and transportation",
    subcategories: [
      { id: "local-moving", name: "Local Moving", description: "In-town residential moving" },
      { id: "long-distance-moving", name: "Long Distance Moving", description: "Interstate and cross-country moving" },
      { id: "hauling-services", name: "Hauling Services", description: "General hauling and transport" },
      { id: "furniture-moving", name: "Furniture Moving", description: "Heavy furniture transport" },
      { id: "appliance-hauling", name: "Appliance Hauling", description: "Appliance pickup and delivery" },
      { id: "debris-hauling", name: "Debris Hauling", description: "Construction debris removal" },
      { id: "dump-runs", name: "Dump Runs", description: "Trips to the dump or recycling center" },
      { id: "packing-unpacking", name: "Packing & Unpacking", description: "Professional packing services" },
      { id: "labor-only-moving", name: "Labor Only Moving", description: "Loading and unloading help" },
      { id: "specialty-moving", name: "Specialty Item Moving", description: "Pianos, safes, and heavy items" },
    ],
  },
  {
    id: "metal-work",
    name: "Metal Work",
    icon: "Hammer",
    description: "Welding, fabrication, and metal services",
    subcategories: [
      { id: "welding", name: "Welding Services", description: "MIG, TIG, and stick welding" },
      { id: "metal-fabrication", name: "Metal Fabrication", description: "Custom metal fabrication" },
      { id: "ornamental-iron", name: "Ornamental Iron", description: "Decorative iron railings and gates" },
      { id: "structural-steel", name: "Structural Steel", description: "Steel beams and structural work" },
      { id: "aluminum-work", name: "Aluminum Work", description: "Aluminum welding and fabrication" },
      { id: "blacksmithing", name: "Blacksmithing", description: "Traditional forging and metalcraft" },
      { id: "sheet-metal", name: "Sheet Metal Work", description: "HVAC ductwork and sheet metal" },
      { id: "metal-railings", name: "Metal Railings & Stairs", description: "Custom railings and staircases" },
      { id: "mobile-welding", name: "Mobile Welding", description: "On-site welding services" },
      { id: "metal-art", name: "Metal Art & Sculpture", description: "Custom metal artwork" },
    ],
  },
  {
    id: "fencing",
    name: "Fencing",
    icon: "Fence",
    description: "Fence installation, repair, and materials",
    subcategories: [
      { id: "wood-fence", name: "Wood Fencing", description: "Privacy, picket, and board fences" },
      { id: "vinyl-fence", name: "Vinyl Fencing", description: "PVC and vinyl fence installation" },
      { id: "chain-link-fence", name: "Chain Link Fencing", description: "Galvanized and coated chain link" },
      { id: "aluminum-fence", name: "Aluminum Fencing", description: "Ornamental aluminum fences" },
      { id: "wrought-iron-fence", name: "Wrought Iron Fencing", description: "Iron fence installation and repair" },
      { id: "fence-repair", name: "Fence Repair", description: "All types of fence repair" },
      { id: "gate-installation", name: "Gate Installation", description: "Driveway and pedestrian gates" },
      { id: "automatic-gates", name: "Automatic Gates", description: "Electric gate openers and access" },
      { id: "farm-fence", name: "Farm & Ranch Fencing", description: "Agricultural and livestock fencing" },
      { id: "commercial-fencing", name: "Commercial Fencing", description: "Business and industrial fencing" },
    ],
  },
  {
    id: "woodworking",
    name: "Woodworking",
    icon: "Hammer",
    description: "Custom woodwork, furniture, and wood crafts",
    subcategories: [
      { id: "custom-furniture", name: "Custom Furniture", description: "Handcrafted furniture pieces" },
      { id: "cabinetry", name: "Custom Cabinetry", description: "Kitchen and bathroom cabinets" },
      { id: "wood-carving", name: "Wood Carving", description: "Decorative wood carving" },
      { id: "wood-turning", name: "Wood Turning", description: "Lathe work and turned items" },
      { id: "wood-restoration", name: "Wood Restoration", description: "Antique and furniture restoration" },
      { id: "wood-finishing", name: "Wood Finishing", description: "Staining, lacquering, and finishing" },
      { id: "wood-signs", name: "Custom Wood Signs", description: "Handmade signage and lettering" },
      { id: "wood-shelving", name: "Shelving & Built-Ins", description: "Custom shelves and built-in units" },
    ],
  },
  {
    id: "entertainment-services",
    name: "Entertainment Services",
    icon: "Music",
    description: "Live music, DJs, performers, and event entertainment",
    subcategories: [
      { id: "live-bands", name: "Live Bands & Musicians", description: "Local bands and solo artists" },
      { id: "djs", name: "DJs", description: "Event and party DJs" },
      { id: "clowns-magicians", name: "Clowns & Magicians", description: "Children's and party entertainers" },
      { id: "comedians", name: "Comedians & MCs", description: "Stand-up comics and event hosts" },
      { id: "karaoke", name: "Karaoke Services", description: "Karaoke equipment and hosting" },
      { id: "face-painting", name: "Face Painting & Balloon Art", description: "Party artists and balloon twisters" },
      { id: "photo-booth", name: "Photo Booth Rentals", description: "Event photo booth services" },
      { id: "sound-lighting", name: "Sound & Lighting", description: "AV equipment rental and setup" },
      { id: "event-performers", name: "Event Performers", description: "Dancers, acrobats, and specialty acts" },
      { id: "party-characters", name: "Party Characters", description: "Costumed character appearances" },
    ],
  },
  {
    id: "entertainment-locations",
    name: "Entertainment Locations",
    icon: "MapPin",
    description: "Venues, attractions, and entertainment destinations",
    subcategories: [
      { id: "bowling-alleys", name: "Bowling Alleys", description: "Bowling lanes and arcades" },
      { id: "movie-theaters", name: "Movie Theaters", description: "Cinema and film screenings" },
      { id: "arcades-gaming", name: "Arcades & Gaming", description: "Video games and amusement centers" },
      { id: "mini-golf", name: "Mini Golf", description: "Miniature golf courses" },
      { id: "go-karts", name: "Go-Karts & Racing", description: "Go-kart tracks and racing" },
      { id: "escape-rooms", name: "Escape Rooms", description: "Puzzle and escape room experiences" },
      { id: "amusement-parks", name: "Amusement Parks", description: "Theme parks and rides" },
      { id: "live-music-venues", name: "Live Music Venues", description: "Concert halls and music bars" },
      { id: "sports-complexes", name: "Sports Complexes", description: "Indoor sports and recreation" },
      { id: "trampoline-parks", name: "Trampoline Parks", description: "Jump parks and indoor fun" },
      { id: "museums-galleries", name: "Museums & Galleries", description: "Art, history, and science museums" },
      { id: "water-parks", name: "Water Parks", description: "Water slides and splash parks" },
    ],
  },
  {
    id: "catering-food-trucks",
    name: "Catering / Food Trucks",
    icon: "Truck",
    description: "Catering services and mobile food vendors",
    subcategories: [
      { id: "wedding-catering", name: "Wedding Catering", description: "Full-service wedding catering" },
      { id: "corporate-catering", name: "Corporate Catering", description: "Office and corporate event catering" },
      { id: "bbq-catering", name: "BBQ Catering", description: "Barbecue and smoker catering" },
      { id: "food-trucks-mobile", name: "Food Trucks", description: "Mobile food vendors and trucks" },
      { id: "dessert-catering", name: "Dessert Catering", description: "Cakes, cookies, and dessert bars" },
      { id: "taco-trucks", name: "Taco Trucks", description: "Mexican and taco food trucks" },
      { id: "seafood-catering", name: "Seafood Catering", description: "Fresh seafood catering and boils" },
      { id: "party-platters", name: "Party Platters & Trays", description: "Prepared platters for events" },
    ],
  },
  {
    id: "concrete",
    name: "Concrete",
    icon: "Hammer",
    description: "Concrete contractors, driveways, patios, and foundations",
    subcategories: [
      { id: "concrete-driveways", name: "Driveways", description: "Concrete driveway installation and repair" },
      { id: "concrete-patios", name: "Patios & Walkways", description: "Concrete patio and walkway construction" },
      { id: "concrete-foundations", name: "Foundations", description: "Foundation work and repair" },
      { id: "concrete-stamped", name: "Stamped & Decorative", description: "Decorative and stamped concrete" },
      { id: "concrete-retaining-walls", name: "Retaining Walls", description: "Concrete retaining wall construction" },
    ],
  },
  {
    id: "realtors",
    name: "Realtors",
    icon: "Home",
    description: "Licensed real estate agents and brokers",
    subcategories: [
      { id: "realtors-residential", name: "Residential Realtors", description: "Home buying and selling agents" },
      { id: "realtors-commercial", name: "Commercial Realtors", description: "Commercial property agents" },
      { id: "realtors-land", name: "Land & Lots", description: "Vacant land and lot sales" },
      { id: "realtors-rental", name: "Rental Agents", description: "Rental property management and leasing" },
    ],
  },
  {
    id: "embroidery-alterations",
    name: "Embroidery / Alterations",
    icon: "Scissors",
    description: "Custom embroidery, sewing, and clothing alterations",
    subcategories: [
      { id: "embroidery-custom", name: "Custom Embroidery", description: "Personalized embroidery services" },
      { id: "alterations-clothing", name: "Clothing Alterations", description: "Hemming, tailoring, and fitting" },
      { id: "alterations-formal", name: "Formal Wear Alterations", description: "Wedding dress and formal wear alterations" },
      { id: "embroidery-monogram", name: "Monogramming", description: "Monogram and personalization services" },
    ],
  },
  {
    id: "flooring",
    name: "Flooring",
    icon: "LayoutGrid",
    description: "Flooring installation, refinishing, and repair",
    subcategories: [
      { id: "flooring-hardwood", name: "Hardwood", description: "Hardwood floor installation and refinishing" },
      { id: "flooring-tile", name: "Tile", description: "Ceramic and porcelain tile installation" },
      { id: "flooring-carpet", name: "Carpet", description: "Carpet installation and cleaning" },
      { id: "flooring-vinyl", name: "Vinyl & Laminate", description: "LVP, laminate, and vinyl flooring" },
      { id: "flooring-epoxy", name: "Epoxy & Coating", description: "Garage and basement epoxy coatings" },
    ],
  },
  {
    id: "painting",
    name: "Painting",
    icon: "Paintbrush",
    description: "Interior and exterior painting services",
    subcategories: [
      { id: "painting-interior", name: "Interior Painting", description: "Walls, ceilings, and trim" },
      { id: "painting-exterior", name: "Exterior Painting", description: "House exteriors, decks, and fences" },
      { id: "painting-commercial", name: "Commercial Painting", description: "Office and commercial spaces" },
      { id: "painting-cabinets", name: "Cabinet Refinishing", description: "Kitchen and bathroom cabinet painting" },
      { id: "painting-staining", name: "Staining & Sealing", description: "Wood staining and deck sealing" },
    ],
  },
  {
    id: "printing",
    name: "Printing",
    icon: "Printer",
    description: "Print shops, sign making, and promotional materials",
    subcategories: [
      { id: "printing-signs", name: "Signs & Banners", description: "Custom signs, banners, and vehicle wraps" },
      { id: "printing-business", name: "Business Printing", description: "Business cards, brochures, and flyers" },
      { id: "printing-apparel", name: "Custom Apparel", description: "T-shirt and apparel printing" },
      { id: "printing-large-format", name: "Large Format", description: "Posters, canvases, and large prints" },
    ],
  },
  {
    id: "home-repair",
    name: "Home Repair",
    icon: "Wrench",
    description: "General home repair and handyman services",
    subcategories: [
      { id: "home-repair-handyman", name: "Handyman", description: "General repairs and odd jobs" },
      { id: "home-repair-drywall", name: "Drywall Repair", description: "Drywall patching and installation" },
      { id: "home-repair-doors-windows", name: "Doors & Windows", description: "Door and window repair or replacement" },
      { id: "home-repair-siding", name: "Siding", description: "Siding repair and installation" },
      { id: "home-repair-decks", name: "Decks & Porches", description: "Deck and porch repair and building" },
    ],
  },
  {
    id: "new-construction",
    name: "New Construction",
    icon: "HardHat",
    description: "New home and building construction",
    subcategories: [
      { id: "new-construction-residential", name: "Residential Construction", description: "Custom home building" },
      { id: "new-construction-commercial", name: "Commercial Construction", description: "Commercial building construction" },
      { id: "new-construction-garage", name: "Garages & Outbuildings", description: "Detached garages and shops" },
      { id: "new-construction-modular", name: "Modular & Manufactured", description: "Modular and manufactured homes" },
    ],
  },
  {
    id: "remodeling",
    name: "New Addition / Remodeling",
    icon: "PencilRuler",
    description: "Home additions, renovations, and remodeling",
    subcategories: [
      { id: "remodeling-kitchen", name: "Kitchen Remodeling", description: "Kitchen renovations and upgrades" },
      { id: "remodeling-bathroom", name: "Bathroom Remodeling", description: "Bathroom renovations and upgrades" },
      { id: "remodeling-basement", name: "Basement Finishing", description: "Basement finishing and conversions" },
      { id: "remodeling-additions", name: "Room Additions", description: "Home additions and expansions" },
      { id: "remodeling-whole-home", name: "Whole Home Renovation", description: "Full home renovation projects" },
    ],
  },
  {
    id: "tree-services",
    name: "Tree Services",
    icon: "TreePine",
    description: "Tree removal, trimming, and stump grinding",
    subcategories: [
      { id: "tree-removal", name: "Tree Removal", description: "Full tree removal services" },
      { id: "tree-trimming", name: "Tree Trimming", description: "Pruning and shaping" },
      { id: "tree-stump", name: "Stump Grinding", description: "Stump removal and grinding" },
      { id: "tree-emergency", name: "Emergency Tree Service", description: "Storm damage and emergency removal" },
    ],
  },
  {
    id: "pool-spa",
    name: "Pool & Spa",
    icon: "Waves",
    description: "Pool and spa installation, maintenance, and repair",
    subcategories: [
      { id: "pool-installation", name: "Pool Installation", description: "In-ground and above-ground pool installation" },
      { id: "pool-maintenance", name: "Pool Maintenance", description: "Cleaning, chemical balancing, and upkeep" },
      { id: "pool-repair", name: "Pool Repair", description: "Liner, pump, and equipment repair" },
      { id: "spa-hot-tub", name: "Hot Tubs & Spas", description: "Hot tub sales, installation, and service" },
    ],
  },
  {
    id: "baking-cooking",
    name: "Baking / Cooking",
    icon: "CakeSlice",
    description: "Home bakers, personal chefs, and cooking services",
    subcategories: [
      { id: "baking-cakes", name: "Custom Cakes", description: "Birthday, wedding, and specialty cakes" },
      { id: "baking-pastries", name: "Pastries & Baked Goods", description: "Cookies, pies, breads, and more" },
      { id: "cooking-personal-chef", name: "Personal Chef", description: "In-home personal chef services" },
      { id: "cooking-meal-prep", name: "Meal Prep", description: "Weekly meal preparation services" },
    ],
  },
  {
    id: "roofing",
    name: "Roofing",
    icon: "Home",
    description: "Roof installation, repair, and inspection",
    subcategories: [
      { id: "roofing-shingle", name: "Shingle Roofing", description: "Asphalt shingle installation and repair" },
      { id: "roofing-metal", name: "Metal Roofing", description: "Standing seam and metal roof systems" },
      { id: "roofing-flat", name: "Flat Roofing", description: "Commercial and flat roof systems" },
      { id: "roofing-repair", name: "Roof Repair", description: "Leak repair and damage restoration" },
      { id: "roofing-gutter", name: "Gutters & Downspouts", description: "Gutter installation and cleaning" },
    ],
  },
  {
    id: "hvac",
    name: "HVAC",
    icon: "Thermometer",
    description: "Heating, ventilation, and air conditioning services",
    subcategories: [
      { id: "hvac-installation", name: "HVAC Installation", description: "New system installation" },
      { id: "hvac-repair", name: "HVAC Repair", description: "System diagnostics and repair" },
      { id: "hvac-maintenance", name: "HVAC Maintenance", description: "Seasonal tune-ups and filter changes" },
      { id: "hvac-ductwork", name: "Ductwork", description: "Duct cleaning, repair, and installation" },
      { id: "hvac-heat-pump", name: "Heat Pumps", description: "Heat pump installation and service" },
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "Droplets",
    description: "Plumbing installation, repair, and drain services",
    subcategories: [
      { id: "plumbing-repair", name: "Plumbing Repair", description: "Fixture and pipe repair" },
      { id: "plumbing-drain", name: "Drain Cleaning", description: "Clog removal and drain clearing" },
      { id: "plumbing-water-heater", name: "Water Heaters", description: "Water heater installation and repair" },
      { id: "plumbing-sewer", name: "Sewer Lines", description: "Sewer line inspection and repair" },
      { id: "plumbing-new", name: "New Construction Plumbing", description: "Rough-in and finish plumbing" },
    ],
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "Zap",
    description: "Electrical installation, repair, and wiring services",
    subcategories: [
      { id: "electrical-residential", name: "Residential Electrical", description: "Home wiring and outlets" },
      { id: "electrical-commercial", name: "Commercial Electrical", description: "Commercial wiring and power" },
      { id: "electrical-panel", name: "Panel Upgrades", description: "Breaker panel replacement and upgrades" },
      { id: "electrical-lighting", name: "Lighting", description: "Indoor, outdoor, and landscape lighting" },
      { id: "electrical-generator", name: "Generators", description: "Generator installation and maintenance" },
    ],
  },
  {
    id: "trash-junk-removal",
    name: "Trash / Junk Removal",
    icon: "Trash2",
    description: "Junk hauling, dumpster rental, and waste removal",
    subcategories: [
      { id: "junk-residential", name: "Residential Junk Removal", description: "Home cleanout and junk hauling" },
      { id: "junk-commercial", name: "Commercial Cleanout", description: "Office and commercial cleanout" },
      { id: "junk-dumpster", name: "Dumpster Rental", description: "Roll-off dumpster rental" },
      { id: "junk-debris", name: "Construction Debris", description: "Demolition and construction waste" },
    ],
  },
  {
    id: "web-logo-design",
    name: "Web / Logo Design",
    icon: "Palette",
    description: "Website design, logo creation, and digital branding",
    subcategories: [
      { id: "web-design", name: "Website Design", description: "Custom website design and development" },
      { id: "logo-design", name: "Logo Design", description: "Brand logo creation and identity" },
      { id: "graphic-design", name: "Graphic Design", description: "Marketing materials and graphics" },
      { id: "social-media-design", name: "Social Media Design", description: "Social media graphics and branding" },
    ],
  },
  {
    id: "auto-detailing",
    name: "Auto Detailing",
    icon: "Car",
    description: "Car detailing, paint correction, and interior cleaning",
    subcategories: [
      { id: "detailing-full", name: "Full Detail", description: "Complete interior and exterior detail" },
      { id: "detailing-interior", name: "Interior Detail", description: "Deep cleaning, shampoo, and conditioning" },
      { id: "detailing-exterior", name: "Exterior Detail", description: "Wash, clay bar, polish, and wax" },
      { id: "detailing-ceramic", name: "Ceramic Coating", description: "Ceramic coating and paint protection" },
      { id: "detailing-mobile", name: "Mobile Detailing", description: "On-site mobile detailing services" },
    ],
  },
  {
    id: "window-tinting",
    name: "Window Tinting",
    icon: "Sun",
    description: "Automotive, residential, and commercial window tinting",
    subcategories: [
      { id: "tinting-auto", name: "Auto Tinting", description: "Car and truck window tinting" },
      { id: "tinting-residential", name: "Residential Tinting", description: "Home window film installation" },
      { id: "tinting-commercial", name: "Commercial Tinting", description: "Office and commercial building tinting" },
      { id: "tinting-ppf", name: "Paint Protection Film", description: "Clear bra and paint protection film" },
    ],
  },
  {
    id: "appliance-repair",
    name: "Appliance Repair",
    icon: "Refrigerator",
    description: "Home and commercial appliance repair services",
    subcategories: [
      { id: "appliance-kitchen", name: "Kitchen Appliances", description: "Refrigerator, oven, dishwasher repair" },
      { id: "appliance-laundry", name: "Washer & Dryer", description: "Washing machine and dryer repair" },
      { id: "appliance-hvac-units", name: "HVAC Units", description: "Window units and portable AC repair" },
      { id: "appliance-commercial", name: "Commercial Appliances", description: "Restaurant and commercial equipment" },
    ],
  },
  {
    id: "pressure-washing",
    name: "Pressure Washing",
    icon: "Droplets",
    description: "Power washing for homes, driveways, and commercial properties",
    subcategories: [
      { id: "pressure-house", name: "House Washing", description: "Siding, brick, and exterior cleaning" },
      { id: "pressure-driveway", name: "Driveway & Sidewalk", description: "Concrete and paver cleaning" },
      { id: "pressure-deck", name: "Deck & Fence", description: "Deck, fence, and patio cleaning" },
      { id: "pressure-commercial", name: "Commercial Washing", description: "Building and parking lot washing" },
      { id: "pressure-roof", name: "Roof Cleaning", description: "Soft wash roof cleaning" },
    ],
  },
  {
    id: "food-drink",
    name: "Food & Drink",
    icon: "Coffee",
    description: "Bars, breweries, bakeries, and specialty food shops",
    subcategories: [
      { id: "food-bars", name: "Bars & Pubs", description: "Local bars and pubs" },
      { id: "food-brewery", name: "Breweries & Wineries", description: "Craft breweries and local wineries" },
      { id: "food-bakery", name: "Bakeries", description: "Bread, pastries, and baked goods shops" },
      { id: "food-specialty", name: "Specialty Food", description: "Gourmet, organic, and specialty food shops" },
      { id: "food-ice-cream", name: "Ice Cream & Frozen Treats", description: "Ice cream shops and frozen desserts" },
    ],
  },
  {
    id: "tax-cpa",
    name: "Tax / CPA",
    icon: "Calculator",
    description: "Tax preparation, accounting, and CPA services",
    subcategories: [
      { id: "tax-personal", name: "Personal Tax Prep", description: "Individual tax return preparation" },
      { id: "tax-business", name: "Business Tax", description: "Business tax preparation and planning" },
      { id: "tax-bookkeeping", name: "Bookkeeping", description: "Bookkeeping and payroll services" },
      { id: "tax-audit", name: "Audit & Compliance", description: "Tax audit representation and compliance" },
    ],
  },
  {
    id: "babysitting-nanny",
    name: "Babysitting / Nanny",
    icon: "Baby",
    description: "Babysitters, nannies, and in-home childcare providers",
    subcategories: [
      { id: "babysitting-occasional", name: "Occasional Babysitting", description: "Date night and event babysitting" },
      { id: "nanny-fulltime", name: "Full-Time Nanny", description: "Full-time in-home nanny services" },
      { id: "nanny-parttime", name: "Part-Time Nanny", description: "Part-time and after-school care" },
      { id: "nanny-newborn", name: "Newborn Care", description: "Infant and newborn specialists" },
    ],
  },
  {
    id: "tutoring-mentoring",
    name: "Tutor / Mentor / Counseling",
    icon: "GraduationCap",
    description: "Academic tutoring, mentoring, and counseling services",
    subcategories: [
      { id: "tutor-academic", name: "Academic Tutoring", description: "Math, science, reading, and test prep" },
      { id: "tutor-music", name: "Music Lessons", description: "Instrument and voice lessons" },
      { id: "mentor-life-coach", name: "Life Coaching", description: "Personal development and life coaching" },
      { id: "counseling-therapy", name: "Counseling & Therapy", description: "Licensed counselors and therapists" },
      { id: "mentor-career", name: "Career Mentoring", description: "Career guidance and professional mentoring" },
    ],
  },
  {
    id: "event-rentals",
    name: "Event Rentals",
    icon: "Tent",
    description: "Party and event rental equipment and supplies",
    subcategories: [
      { id: "rental-tents", name: "Tents & Canopies", description: "Event tents and canopy rentals" },
      { id: "rental-tables-chairs", name: "Tables & Chairs", description: "Table, chair, and linen rentals" },
      { id: "rental-bounce", name: "Bounce Houses & Inflatables", description: "Kids' entertainment rentals" },
      { id: "rental-audio-visual", name: "Audio & Visual", description: "Sound systems, projectors, and lighting" },
      { id: "rental-photo-booth", name: "Photo Booths", description: "Photo booth and backdrop rentals" },
    ],
  },
];

BUSINESS_CATEGORIES.sort((a, b) => a.name.localeCompare(b.name));

export function getCategoryById(id: string): BusinessCategory | undefined {
  return BUSINESS_CATEGORIES.find((cat) => cat.id === id);
}

export function getSubcategoryById(categoryId: string, subcategoryId: string): Subcategory | undefined {
  const category = getCategoryById(categoryId);
  return category?.subcategories.find((sub) => sub.id === subcategoryId);
}

export function searchCategories(query: string): BusinessCategory[] {
  const lowerQuery = query.toLowerCase();
  return BUSINESS_CATEGORIES.filter(
    (cat) =>
      cat.name.toLowerCase().includes(lowerQuery) ||
      cat.description.toLowerCase().includes(lowerQuery) ||
      cat.subcategories.some(
        (sub) =>
          sub.name.toLowerCase().includes(lowerQuery) ||
          sub.description.toLowerCase().includes(lowerQuery)
      )
  );
}

export function getAllSubcategories(): Subcategory[] {
  return BUSINESS_CATEGORIES.flatMap((cat) => cat.subcategories);
}

export function getCategoryCount(): number {
  return BUSINESS_CATEGORIES.length;
}

export function getSubcategoryCount(): number {
  return BUSINESS_CATEGORIES.reduce((sum, cat) => sum + cat.subcategories.length, 0);
}

export const DIRECTORY_CATEGORY_NAMES: string[] = BUSINESS_CATEGORIES.map(c => c.name).sort();

export const EMERGENCY_CATEGORIES = ["hvac", "electrical", "plumbing", "roofing", "locksmith", "towing", "storm-damage"] as const;

export function isEmergencyCategory(subcategoryId: string): boolean {
  return (EMERGENCY_CATEGORIES as readonly string[]).includes(subcategoryId);
}
